eval: false
onscreen_render: false
ckpt_dir: "data/output/${params.task_name}/${params.backbone}/${params.dataset_cls}/rela_${params.relative_control}/chunk_size_${params.chunk_size}"
policy_class: ""
task_name: ""
batch_size: 8
seed: 0
num_epochs: 8
lr: 1e-5
qpos_noise_std: 0.0
backbone: "dino_v2"
freeze_backbone: true
load_pretrain: false
eval_every: 50000
validate_every: 50000
save_every: 1000
resume_ckpt_path: null
skip_mirrored_data: false
actuator_network_dir: null
history_len: null
future_len: null
prediction_len: null
dataset_cls: "EpisodicDataset"
relative_control: false
action_dim: 9
state_dim: 9
kl_weight: 10
chunk_size: null
hidden_dim: 512
dim_feedforward: 3200
temporal_agg: false
use_vq: false
vq_class: null
vq_dim: null
no_encoder: false
augment_type: 0
augment_prob: 0.5